# If not running interactively, don't do anything
if [[ -n "$PS1" ]]; then
    HISTCONTROL=ignoredups:ignorespace
    HISTSIZE=1000
    HISTFILESIZE=2000

    shopt -s histappend
    shopt -s checkwinsize

    if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
	. /etc/bash_completion
    fi

    for f in ~/.bashrc.d/* ; do
	. $f
    done
fi
