#!/usr/bin/env bash

alias emacss='emacs &'
alias emacsd='emacs --daemon'
alias emacsp='TERM=xterm-256color emacs -nw --insert'
alias emacsc='emacsclient -c'
alias emacst='TERM=xterm-256color emacsclient -t'
