#!/usr/bin/env bash

#
## Rbenv
#
export RBENV_ROOT="$HOME/.rbenv"
export PATH="$RBENV_ROOT/shims:$RBENV_ROOT/bin:$PATH"
source "$RBENV_ROOT/completions/rbenv.bash"
export PATH="$HOME/.rbenv/shims:${PATH}"
export RBENV_SHELL=bash
source "$HOME/.rbenv/completions/rbenv.bash"
rbenv() {
  local command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(rbenv "sh-$command" "$@")";;
  *)
    command rbenv "$command" "$@";;
  esac
}

#
## Bundler
#
export BUNDLER_EDITOR="nautilus"
alias b='bundle'
alias bi='bundle install'
alias be='bundle exec'
alias berdm='bundle exec rake db:migrate'
alias berdmv0='bundle exec rake db:migrate VERSION=0'
alias berdr='bundle exec rake db:rollback'

#
## CTAG
#
alias ctags_ruby='ctags -e -R --languages=ruby --exclude=.git --exclude=log --exclude=.gems .'
alias ctags_bundler='ctags -e -R --languages=ruby --exclude=.git --exclude=log . $(bundle list --paths)'
