#!/bin/bash -e

: ${EMACS_VERSION:="24.4"}
: ${TMP:="$(pwd)/tmp"}
: ${EMACS_DIR:="$TMP/emacs-$EMACS_VERSION"}
: ${EMACS_DOTFILES_REPO:='https://github.com/fernandoalmeida/.emacs.d.git'}

# install dependencies
sudo apt-get install -qq --yes --force-yes \
    wget build-essential libncurses5 libncurses5-dev
sudo apt-get build-dep emacs24 --yes --force-yes -qq

# download and install Emacs (latest) via source code
wget http://ftp.gnu.org/gnu/emacs/emacs-$EMACS_VERSION.tar.gz -nc -P $TMP
tar -C $TMP -zxvf $TMP/emacs-$EMACS_VERSION.tar.gz
cd $EMACS_DIR && ./configure && make && sudo make install
ln -sfn $(pwd)/dotfiles/bashrc.d/emacs $HOME/.bashrc.d/

# download and configure my Emacs dotfiles
git clone $EMACS_DOTFILES_REPO $HOME/.emacs.d
