#!/usr/bin/env bash

export JAVA_HOME=/usr/lib/jvm/java-7-oracle
export ANDROID_STUDIO_HOME=$HOME/trabalho/programas/linux/android_studio/android-studio
export ANDROID_SDK_HOME=$ANDROID_STUDIO_HOME/sdk
export ANDROID_NDK_HOME=$ANDROID_STUDIO_HOME/ndk
export ANDROID_HOME=$ANDROID_SDK_HOME
export PATH=$JAVA_HOME/bin:$ANDROID_STUDIO_HOME/bin:$ANDROID_SDK_HOME/tools:$ANDROID_SDK_HOME/platform-tools:$PATH

alias avd='android avd &'
